import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"

import localFont from "next/font/local"
import { Toaster } from "sonner"

const gtWalsheim = localFont({
	src: [
		{
			path: "./fonts/GT-Walsheim-Black-Trial-BF651b7fc736a5b.otf",
			weight: "900",
			style: "normal",
		},
		{
			path: "./fonts/GT-Walsheim-Black-Oblique-Trial-BF651b7fc5608e6.otf",
			weight: "900",
			style: "oblique",
		},
		{
			path: "./fonts/GT-Walsheim-Bold-Trial-BF651b7fc737c57.otf",
			weight: "700",
			style: "normal",
		},
		{
			path: "./fonts/GT-Walsheim-Bold-Oblique-Trial-BF651b7fc5f06a0.otf",
			weight: "700",
			style: "oblique",
		},
		{
			path: "./fonts/GT-Walsheim-Medium-Trial-BF651b7fc728fb3.otf",
			weight: "500",
			style: "normal",
		},
		{
			path: "./fonts/GT-Walsheim-Medium-Oblique-Trial-BF651b7fc69eff5.otf",
			weight: "500",
			style: "oblique",
		},
		{
			path: "./fonts/GT-Walsheim-Regular-Trial-BF651b7fc71a47d.otf",
			weight: "400",
			style: "normal",
		},
		{
			path: "./fonts/GT-Walsheim-Regular-Oblique-Trial-BF651b7fc67342f.otf",
			weight: "400",
			style: "oblique",
		},
		{
			path: "./fonts/GT-Walsheim-Light-Trial-BF651b7fc714941.otf",
			weight: "300",
			style: "normal",
		},
		{
			path: "./fonts/GT-Walsheim-Light-Oblique-Trial-BF651b7fc6b04a3.otf",
			weight: "300",
			style: "oblique",
		},
		{
			path: "./fonts/GT-Walsheim-Thin-Trial-BF651b7fc728c4c.otf",
			weight: "200",
			style: "normal",
		},
		{
			path: "./fonts/GT-Walsheim-Thin-Oblique-Trial-BF651b7fc66311a.otf",
			weight: "200",
			style: "oblique",
		},
		{
			path: "./fonts/GT-Walsheim-Ultra-Bold-Trial-BF651b7fc6c21e5.otf",
			weight: "800",
			style: "normal",
		},
		{
			path: "./fonts/GT-Walsheim-Ultra-Bold-Oblique-Trial-BF651b7fc60ad12.otf",
			weight: "800",
			style: "oblique",
		},
		{
			path: "./fonts/GT-Walsheim-Ultra-Light-Trial-BF651b7fc72b236.otf",
			weight: "100",
			style: "normal",
		},
		{
			path: "./fonts/GT-Walsheim-Ultra-Light-Oblique-Trial-BF651b7fc635c6e.otf",
			weight: "100",
			style: "oblique",
		},
	],
	variable: "--font-gt-walsheim",
	display: "swap",
})

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
})

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable} ${gtWalsheim.variable} antialiased`}>
				<Toaster position="top-center" />
				{children}
			</body>
		</html>
	)
}
